### ISSUE TITLE
bulid problem

### ISSUE THREAD

**Issue by DyeTime** [veins/space_veins#3]
I met the situation like the screenshots.How can I fix it?Thanks!

![image](https://github.com/user-attachments/assets/7ff283fa-dbd0-4de9-901c-efd1986a440b)
![image](https://github.com/user-attachments/assets/5d9fe652-1ced-4b2e-9f30-cff211a5d729)
![image](https://github.com/user-attachments/assets/1603d329-31c7-492a-9be1-c785b81594e7)

**Comment by m-franke** [comment]
Hi, thanks for your interest in space_Veins,

however, in order to help you I need more information:

- Which version of space_Veins are you running?
- Are you running space_Veins in a Docker Container or in a Singularity Container?
- What are you trying to do? Do you want to run the example? The example does not use the `VeinsInetSampleApplication`.

For running the example, I recommend to follow the steps in the installation guide at [https://sat.car2x.org/documentation/installation/](https://sat.car2x.org/documentation/installation/)

**Comment by DyeTime** [comment]
Thanks for your reply ! I am a learner and want to learn OMNeT++ and satellite by this project.

- I installed ommet++5.6.2 ,veins 5.2,sumo1.8.0 and space_veins 0.3.
- I imported space_Veins in OMNeT++ and tried to run the example,then met the problem like the screenshots from before.
- I followed the steps in the installation guide.But met the error like this screenshot.
![image](https://github.com/user-attachments/assets/ca918784-a0fa-4d7d-ace0-f7960132412e)

**Comment by m-franke** [comment]
If you are using the Docker container, you don't have to install OMNeT++ and the other dependencies on your own.

Further, based on your screenshot it seems to me that you store space_Veins in a Microsoft OS. This is not supported/tested at the moment. I am sorry that the installation guide is not precise enough. I will update it.

I recommend to install the [WSL2](https://learn.microsoft.com/en-us/windows/wsl/about) and clone the repository inside the WSL2 system. Make sure that the [WSL2 backend](https://docs.docker.com/desktop/features/wsl/) is enabled in Docker. Then open the space_Veins root directory in VS Code from inside the WSL2 system by running `code .` inside the space_Veins root directory.

**Comment by DyeTime** [comment]
I get it ! Thanks for your help!
